# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: http://dev.byrobot.co.kr
baseurl: 
title: BYROBOT.DEV
description: "Documents for BYROBOT Products."
keywords: 'Drone,DroneFighters,Petrone,PetroneV2'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: byrobot
      url: http://www.byrobot.co.kr
    - name: facebook
      url: https://www.facebook.com/Byrobot.Drones
    - name: youtube
      url:  https://www.youtube.com/user/BYROBOTCO
    - name: github
      url:  https://github.com/byrobot
    - name: discord
      url:  https://discord.gg/UVVJMye
blog:
  cc_license: https://creativecommons.org/licenses/by-sa/4.0/
  cc_license_image: /assets/images/theme/cc-by-sa.png
  footer_content: Documents for BYROBOT Products.

disqus:
  shortname:
  public_key:
google_analytics: UA-107907956-1
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  products: /products/
  software: /software/
  forum: /forum/